#ifndef __SAMPLEFORMAT_H__
#define __SAMPLEFORMAT_H__

enum SampleFormat {
    SAMPLEFORMAT_AU_8BIT = 0,
    SAMPLEFORMAT_AU_16BIT = 1,
    SAMPLEFORMAT_AU_24BIT = 2,
    SAMPLEFORMAT_AU_32BIT = 3,
    SAMPLEFORMAT_AU_32BIT_FLOAT = 4,
    SAMPLEFORMAT_AIFF_8BIT = 5,
    SAMPLEFORMAT_AIFF_16BIT = 6,
    SAMPLEFORMAT_AIFF_24BIT = 7,
    SAMPLEFORMAT_AIFF_32BIT = 8,
    SAMPLEFORMAT_AIFF_32BIT_FLOAT = 9,
    SAMPLEFORMAT_FLAC_8BIT = 10,
    SAMPLEFORMAT_FLAC_16BIT = 11,
    SAMPLEFORMAT_FLAC_24BIT = 12,
    SAMPLEFORMAT_WAV_8BIT = 13,
    SAMPLEFORMAT_WAV_16BIT = 14,
    SAMPLEFORMAT_WAV_24BIT = 15,
    SAMPLEFORMAT_WAV_32BIT = 16,
    SAMPLEFORMAT_WAV_32BIT_FLOAT = 17
};

#endif
