project(modules)

add_subdirectory(synthclone.app)
add_subdirectory(synthclone.core)
add_subdirectory(synthclone.core.test)
add_subdirectory(synthclone.external.boost.callable_traits)
add_subdirectory(synthclone.external.boost.container)
add_subdirectory(synthclone.external.boost.core)
add_subdirectory(synthclone.external.boost.interprocess)
add_subdirectory(synthclone.external.boost.mp11)
add_subdirectory(synthclone.external.boost.scope)
add_subdirectory(synthclone.external.boost.type_traits)
add_subdirectory(synthclone.external.boost.unit_test)
add_subdirectory(synthclone.external.boost.urls)
add_subdirectory(synthclone.external.kissfft)
add_subdirectory(synthclone.external.posix)
add_subdirectory(synthclone.external.qt.concurrent)
add_subdirectory(synthclone.external.qt.core)
add_subdirectory(synthclone.external.qt.gui)
add_subdirectory(synthclone.external.qt.qml)
add_subdirectory(synthclone.external.qt.quick)
add_subdirectory(synthclone.external.qt.quickcontrols2)
add_subdirectory(synthclone.external.qt.widgets)
add_subdirectory(synthclone.external.samplerate)
add_subdirectory(synthclone.external.sndfile)
add_subdirectory(synthclone.external.utf8proc)
add_subdirectory(synthclone.fx)
add_subdirectory(synthclone.plugin)
add_subdirectory(synthclone.qt)
add_subdirectory(synthclone.qt.test)
add_subdirectory(synthclone.test)
add_subdirectory(synthclone.test.plugin)
add_subdirectory(synthclone.ui)
add_subdirectory(synthclone.util)
