project(modules)

add_subdirectory(synthclone.app)
add_subdirectory(synthclone.core)
add_subdirectory(synthclone.core.test)
add_subdirectory(synthclone.external.boost)
add_subdirectory(synthclone.external.kissfft)
add_subdirectory(synthclone.external.posix)
add_subdirectory(synthclone.external.qt)
add_subdirectory(synthclone.external.samplerate)
add_subdirectory(synthclone.external.sndfile)
add_subdirectory(synthclone.external.utf8proc)
add_subdirectory(synthclone.qt)
add_subdirectory(synthclone.qt.test)
add_subdirectory(synthclone.test)
add_subdirectory(synthclone.util)
