#ifndef __LAYERALGORITHM_H__
#define __LAYERALGORITHM_H__

enum LayerAlgorithm {
    LAYERALGORITHM_LINEAR_INTERPOLATION = 0,
    LAYERALGORITHM_MAXIMUM = 1,
    LAYERALGORITHM_MINIMUM = 2
};

#endif
