#!/usr/bin/env python

from optparse import OptionParser
from os import makedirs
from os.path import dirname, isdir, join

from util import (
    MAJOR_VERSION,
    MINOR_VERSION,
    getResourcesDirectory,
    getTemplatesDirectory,
    writeTemplate
)

def main():
    parser = OptionParser("usage: %prog [options]")
    parser.add_option("-d", "--desktop-file", action="store",
                      default=join(getResourcesDirectory(),
                                   "synthclone.desktop"),
                      dest="desktopFile", help="Desktop file destination")
    parser.add_option("-p", "--prefix", action="store", default="/usr/local",
                      dest="prefix", help="Install prefix")
    options, args = parser.parse_args()
    if len(args):
        parser.error("incorrect number of required arguments")
    desktopFile = options.desktopFile
    desktopDir = dirname(desktopFile)
    if not isdir(desktopDir):
        makedirs(desktopDir)
    data = {
        "majorVersion": MAJOR_VERSION,
        "minorVersion": MINOR_VERSION,
        "prefix": options.prefix
    }
    writeTemplate(desktopFile,
                  join(getTemplatesDirectory(), "synthclone.desktop"), data)

if __name__ == "__main__":
    main()
