// This code was auto-generated at:
//
//     2025-12-04 19:02:11.570122+00:00
//
// Do *not* edit this code.  Any changes made to this code will be lost.

#include <boost/test/unit_test.hpp>

import std;

import synthclone.core;
import synthclone.test;

BOOST_AUTO_TEST_SUITE(midi_gen)

BOOST_AUTO_TEST_CASE(midi_control_index_is_channel_mode)
{
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(0)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(1)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(2)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(3)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(4)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(5)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(6)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(7)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(8)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(9)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(10)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(11)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(12)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(13)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(14)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(15)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(16)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(17)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(18)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(19)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(20)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(21)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(22)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(23)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(24)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(25)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(26)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(27)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(28)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(29)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(30)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(31)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(32)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(33)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(34)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(35)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(36)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(37)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(38)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(39)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(40)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(41)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(42)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(43)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(44)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(45)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(46)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(47)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(48)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(49)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(50)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(51)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(52)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(53)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(54)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(55)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(56)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(57)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(58)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(59)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(60)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(61)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(62)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(63)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(64)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(65)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(66)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(67)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(68)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(69)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(70)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(71)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(72)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(73)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(74)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(75)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(76)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(77)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(78)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(79)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(80)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(81)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(82)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(83)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(84)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(85)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(86)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(87)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(88)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(89)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(90)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(91)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(92)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(93)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(94)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(95)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(96)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(97)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(98)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(99)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(100)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(101)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(102)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(103)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(104)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(105)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(106)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(107)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(108)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(109)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(110)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(111)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(112)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(113)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(114)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(115)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(116)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(117)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(118)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(119)), false);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(120)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(121)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(122)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(123)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(124)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(125)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(126)), true);
    synthclone::verify_eq(is_channel_mode(synthclone::midi_control_index(127)), true);
}

BOOST_AUTO_TEST_CASE(midi_control_index_get_name)
{
    synthclone::verify_eq(get_name(synthclone::midi_control_index(0)), std::string_view("Bank Select"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(1)), std::string_view("Modulation Wheel or Lever"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(2)), std::string_view("Breath Controller"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(3)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(4)), std::string_view("Foot Controller"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(5)), std::string_view("Portamento Time"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(6)), std::string_view("Data Entry MSB"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(7)), std::string_view("Channel Volume"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(8)), std::string_view("Balance"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(9)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(10)), std::string_view("Pan"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(11)), std::string_view("Expression Controller"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(12)), std::string_view("Effect Control 1"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(13)), std::string_view("Effect Control 2"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(14)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(15)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(16)), std::string_view("General Purpose Controller 1"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(17)), std::string_view("General Purpose Controller 2"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(18)), std::string_view("General Purpose Controller 3"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(19)), std::string_view("General Purpose Controller 4"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(20)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(21)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(22)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(23)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(24)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(25)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(26)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(27)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(28)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(29)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(30)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(31)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(32)), std::string_view("LSB for Control 0 (Bank Select)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(33)), std::string_view("LSB for Control 1 (Modulation Wheel or Lever)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(34)), std::string_view("LSB for Control 2 (Breath Controller)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(35)), std::string_view("LSB for Control 3 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(36)), std::string_view("LSB for Control 4 (Foot Controller)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(37)), std::string_view("LSB for Control 5 (Portamento Time)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(38)), std::string_view("LSB for Control 6 (Data Entry)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(39)), std::string_view("LSB for Control 7 (Channel Volume)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(40)), std::string_view("LSB for Control 8 (Balance)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(41)), std::string_view("LSB for Control 9 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(42)), std::string_view("LSB for Control 10 (Pan)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(43)), std::string_view("LSB for Control 11 (Expression Controller)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(44)), std::string_view("LSB for Control 12 (Effect control 1)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(45)), std::string_view("LSB for Control 13 (Effect control 2)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(46)), std::string_view("LSB for Control 14 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(47)), std::string_view("LSB for Control 15 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(48)), std::string_view("LSB for Control 16 (General Purpose Controller 1)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(49)), std::string_view("LSB for Control 17 (General Purpose Controller 2)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(50)), std::string_view("LSB for Control 18 (General Purpose Controller 3)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(51)), std::string_view("LSB for Control 19 (General Purpose Controller 4)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(52)), std::string_view("LSB for Control 20 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(53)), std::string_view("LSB for Control 21 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(54)), std::string_view("LSB for Control 22 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(55)), std::string_view("LSB for Control 23 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(56)), std::string_view("LSB for Control 24 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(57)), std::string_view("LSB for Control 25 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(58)), std::string_view("LSB for Control 26 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(59)), std::string_view("LSB for Control 27 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(60)), std::string_view("LSB for Control 28 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(61)), std::string_view("LSB for Control 29 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(62)), std::string_view("LSB for Control 30 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(63)), std::string_view("LSB for Control 31 (Undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(64)), std::string_view("Damper Pedal on/off (Sustain)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(65)), std::string_view("Portamento On/Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(66)), std::string_view("Sostenuto On/Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(67)), std::string_view("Soft Pedal On/Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(68)), std::string_view("Legato Footswitch"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(69)), std::string_view("Hold 2"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(70)), std::string_view("Sound Controller 1 (default: Sound Variation)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(71)), std::string_view("Sound Controller 2 (default: Timbre/Harmonic Intens.)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(72)), std::string_view("Sound Controller 3 (default: Release Time)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(73)), std::string_view("Sound Controller 4 (default: Attack Time)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(74)), std::string_view("Sound Controller 5 (default: Brightness)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(75)), std::string_view("Sound Controller 6 (default: Decay Time)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(76)), std::string_view("Sound Controller 7 (default: Vibrato Rate)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(77)), std::string_view("Sound Controller 8 (default: Vibrato Depth)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(78)), std::string_view("Sound Controller 9 (default: Vibrato Delay)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(79)), std::string_view("Sound Controller 10 (default undefined)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(80)), std::string_view("General Purpose Controller 5"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(81)), std::string_view("General Purpose Controller 6"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(82)), std::string_view("General Purpose Controller 7"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(83)), std::string_view("General Purpose Controller 8"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(84)), std::string_view("Portamento Control"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(85)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(86)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(87)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(88)), std::string_view("High Resolution Velocity Prefix"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(89)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(90)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(91)), std::string_view("Effects 1 Depth (default: Reverb Send Level)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(92)), std::string_view("Effects 2 Depth"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(93)), std::string_view("Effects 3 Depth (default: Chorus Send Level)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(94)), std::string_view("Effects 4 Depth"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(95)), std::string_view("Effects 5 Depth"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(96)), std::string_view("Data Increment (Data Entry +1)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(97)), std::string_view("Data Decrement (Data Entry -1)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(98)), std::string_view("Non-Registered Parameter Number (NRPN) \U00002013 LSB"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(99)), std::string_view("Non-Registered Parameter Number (NRPN) \U00002013 MSB"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(100)), std::string_view("Registered Parameter Number (RPN) \U00002013 LSB"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(101)), std::string_view("Registered Parameter Number (RPN) \U00002013 MSB"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(102)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(103)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(104)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(105)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(106)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(107)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(108)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(109)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(110)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(111)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(112)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(113)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(114)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(115)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(116)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(117)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(118)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(119)), std::string_view("Undefined"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(120)), std::string_view("[Channel Mode Message] All Sound Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(121)), std::string_view("[Channel Mode Message] Reset All Controllers"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(122)), std::string_view("[Channel Mode Message] Local Control On/Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(123)), std::string_view("[Channel Mode Message] All Notes Off"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(124)), std::string_view("[Channel Mode Message] Omni Mode Off (+ all notes off)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(125)), std::string_view("[Channel Mode Message] Omni Mode On (+ all notes off)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(126)), std::string_view("[Channel Mode Message] Mono Mode On (+ poly off, + all notes off)"));
    synthclone::verify_eq(get_name(synthclone::midi_control_index(127)), std::string_view("[Channel Mode Message] Poly Mode On (+ mono off, +all notes off)"));
}

BOOST_AUTO_TEST_CASE(midi_control_type_identifiers)
{
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::undefined), std::string_view("undefined"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::command), std::string_view("command"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::continuous), std::string_view("continuous"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::local), std::string_view("local"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::mono_mode), std::string_view("mono_mode"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::step), std::string_view("step"));
    synthclone::verify_eq(synthclone::get_identifier(synthclone::midi_control_type::toggle), std::string_view("toggle"));
}

BOOST_AUTO_TEST_CASE(midi_control_index_get_type)
{
    synthclone::verify_eq(get_type(synthclone::midi_control_index(0)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(1)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(2)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(3)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(4)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(5)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(6)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(7)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(8)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(9)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(10)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(11)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(12)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(13)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(14)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(15)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(16)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(17)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(18)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(19)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(20)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(21)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(22)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(23)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(24)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(25)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(26)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(27)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(28)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(29)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(30)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(31)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(32)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(33)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(34)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(35)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(36)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(37)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(38)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(39)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(40)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(41)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(42)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(43)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(44)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(45)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(46)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(47)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(48)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(49)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(50)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(51)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(52)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(53)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(54)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(55)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(56)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(57)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(58)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(59)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(60)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(61)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(62)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(63)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(64)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(65)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(66)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(67)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(68)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(69)), synthclone::midi_control_type::toggle);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(70)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(71)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(72)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(73)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(74)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(75)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(76)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(77)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(78)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(79)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(80)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(81)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(82)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(83)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(84)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(85)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(86)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(87)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(88)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(89)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(90)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(91)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(92)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(93)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(94)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(95)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(96)), synthclone::midi_control_type::step);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(97)), synthclone::midi_control_type::step);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(98)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(99)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(100)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(101)), synthclone::midi_control_type::continuous);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(102)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(103)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(104)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(105)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(106)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(107)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(108)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(109)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(110)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(111)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(112)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(113)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(114)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(115)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(116)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(117)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(118)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(119)), synthclone::midi_control_type::undefined);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(120)), synthclone::midi_control_type::command);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(121)), synthclone::midi_control_type::command);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(122)), synthclone::midi_control_type::local);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(123)), synthclone::midi_control_type::command);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(124)), synthclone::midi_control_type::command);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(125)), synthclone::midi_control_type::command);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(126)), synthclone::midi_control_type::mono_mode);
    synthclone::verify_eq(get_type(synthclone::midi_control_index(127)), synthclone::midi_control_type::command);
}

BOOST_AUTO_TEST_CASE(midi_note_get_name)
{
    synthclone::verify_eq(get_name(synthclone::midi_note(0)), std::string_view("C-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(1)), std::string_view("C#-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(2)), std::string_view("D-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(3)), std::string_view("D#-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(4)), std::string_view("E-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(5)), std::string_view("F-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(6)), std::string_view("F#-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(7)), std::string_view("G-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(8)), std::string_view("G#-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(9)), std::string_view("A-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(10)), std::string_view("A#-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(11)), std::string_view("B-1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(12)), std::string_view("C0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(13)), std::string_view("C#0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(14)), std::string_view("D0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(15)), std::string_view("D#0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(16)), std::string_view("E0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(17)), std::string_view("F0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(18)), std::string_view("F#0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(19)), std::string_view("G0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(20)), std::string_view("G#0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(21)), std::string_view("A0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(22)), std::string_view("A#0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(23)), std::string_view("B0"));
    synthclone::verify_eq(get_name(synthclone::midi_note(24)), std::string_view("C1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(25)), std::string_view("C#1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(26)), std::string_view("D1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(27)), std::string_view("D#1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(28)), std::string_view("E1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(29)), std::string_view("F1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(30)), std::string_view("F#1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(31)), std::string_view("G1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(32)), std::string_view("G#1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(33)), std::string_view("A1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(34)), std::string_view("A#1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(35)), std::string_view("B1"));
    synthclone::verify_eq(get_name(synthclone::midi_note(36)), std::string_view("C2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(37)), std::string_view("C#2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(38)), std::string_view("D2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(39)), std::string_view("D#2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(40)), std::string_view("E2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(41)), std::string_view("F2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(42)), std::string_view("F#2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(43)), std::string_view("G2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(44)), std::string_view("G#2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(45)), std::string_view("A2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(46)), std::string_view("A#2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(47)), std::string_view("B2"));
    synthclone::verify_eq(get_name(synthclone::midi_note(48)), std::string_view("C3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(49)), std::string_view("C#3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(50)), std::string_view("D3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(51)), std::string_view("D#3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(52)), std::string_view("E3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(53)), std::string_view("F3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(54)), std::string_view("F#3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(55)), std::string_view("G3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(56)), std::string_view("G#3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(57)), std::string_view("A3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(58)), std::string_view("A#3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(59)), std::string_view("B3"));
    synthclone::verify_eq(get_name(synthclone::midi_note(60)), std::string_view("C4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(61)), std::string_view("C#4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(62)), std::string_view("D4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(63)), std::string_view("D#4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(64)), std::string_view("E4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(65)), std::string_view("F4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(66)), std::string_view("F#4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(67)), std::string_view("G4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(68)), std::string_view("G#4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(69)), std::string_view("A4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(70)), std::string_view("A#4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(71)), std::string_view("B4"));
    synthclone::verify_eq(get_name(synthclone::midi_note(72)), std::string_view("C5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(73)), std::string_view("C#5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(74)), std::string_view("D5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(75)), std::string_view("D#5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(76)), std::string_view("E5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(77)), std::string_view("F5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(78)), std::string_view("F#5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(79)), std::string_view("G5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(80)), std::string_view("G#5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(81)), std::string_view("A5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(82)), std::string_view("A#5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(83)), std::string_view("B5"));
    synthclone::verify_eq(get_name(synthclone::midi_note(84)), std::string_view("C6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(85)), std::string_view("C#6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(86)), std::string_view("D6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(87)), std::string_view("D#6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(88)), std::string_view("E6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(89)), std::string_view("F6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(90)), std::string_view("F#6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(91)), std::string_view("G6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(92)), std::string_view("G#6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(93)), std::string_view("A6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(94)), std::string_view("A#6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(95)), std::string_view("B6"));
    synthclone::verify_eq(get_name(synthclone::midi_note(96)), std::string_view("C7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(97)), std::string_view("C#7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(98)), std::string_view("D7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(99)), std::string_view("D#7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(100)), std::string_view("E7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(101)), std::string_view("F7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(102)), std::string_view("F#7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(103)), std::string_view("G7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(104)), std::string_view("G#7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(105)), std::string_view("A7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(106)), std::string_view("A#7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(107)), std::string_view("B7"));
    synthclone::verify_eq(get_name(synthclone::midi_note(108)), std::string_view("C8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(109)), std::string_view("C#8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(110)), std::string_view("D8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(111)), std::string_view("D#8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(112)), std::string_view("E8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(113)), std::string_view("F8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(114)), std::string_view("F#8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(115)), std::string_view("G8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(116)), std::string_view("G#8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(117)), std::string_view("A8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(118)), std::string_view("A#8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(119)), std::string_view("B8"));
    synthclone::verify_eq(get_name(synthclone::midi_note(120)), std::string_view("C9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(121)), std::string_view("C#9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(122)), std::string_view("D9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(123)), std::string_view("D#9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(124)), std::string_view("E9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(125)), std::string_view("F9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(126)), std::string_view("F#9"));
    synthclone::verify_eq(get_name(synthclone::midi_note(127)), std::string_view("G9"));
}

BOOST_AUTO_TEST_SUITE_END()
