#ifndef __PARTICIPANTTREECOLUMN_H__
#define __PARTICIPANTTREECOLUMN_H__

enum ParticipantTreeColumn {
    PARTICIPANTTREECOLUMN_NAME = 0,
    PARTICIPANTTREECOLUMN_STATE = 1,
    PARTICIPANTTREECOLUMN_VERSION = 2,
    PARTICIPANTTREECOLUMN_AUTHOR = 3,
    PARTICIPANTTREECOLUMN_SUMMARY = 4,

    PARTICIPANTTREECOLUMN_TOTAL = 5
};

#endif
