#ifndef __ZONETABLECOLUMN_H__
#define __ZONETABLECOLUMN_H__

enum ZoneTableColumn {
    ZONETABLECOLUMN_STATUS = 0,
    ZONETABLECOLUMN_CHANNEL = 1,
    ZONETABLECOLUMN_NOTE = 2,
    ZONETABLECOLUMN_VELOCITY = 3,
    ZONETABLECOLUMN_AFTERTOUCH = 4,
    ZONETABLECOLUMN_CONTROL_0 = 5,
    ZONETABLECOLUMN_CONTROL_127 = 132,
    ZONETABLECOLUMN_SAMPLE_TIME = 133,
    ZONETABLECOLUMN_RELEASE_TIME = 134,
    ZONETABLECOLUMN_DRY_SAMPLE = 135,
    ZONETABLECOLUMN_WET_SAMPLE = 136,
    ZONETABLECOLUMN_BASE_TOTAL = 137
};

#endif
